particles:
  activation: true
  deactivation: true
  ambient: true
  ambient-interval-ticks: 5
  cleave: true
  dismantle: true

sounds:
  activation: true
  deactivation: true
  replace-block: true
  cleave: true
  dismantle: true

debug:
  enabled: false
  blocks-per-tick: 1000

disabled-worlds: []
