package dev.nguyendevs.malevolentshrine.schematic;

import org.bukkit.Bukkit;
import org.bukkit.World;
import org.bukkit.block.data.BlockData;
import dev.nguyendevs.malevolentshrine.domain.BlockPos;
import java.util.Base64;
import java.util.HashSet;
import java.util.Set;
import java.util.zip.Inflater;

public class ShrineSchematic {
    private static final int W = 43, H = 54, L = 45;

    private static final BlockData[] PALETTE = new BlockData[456];
    private static final byte[] DATA;

    static {
        String[] paletteStrs = {
            "minecraft:air",
            "minecraft:netherrack",
            "minecraft:magma_block",
            "minecraft:blackstone_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:blackstone_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:black_stained_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true]",
            "minecraft:black_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:crimson_trapdoor[facing=north,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:black_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:blackstone_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:crimson_trapdoor[facing=east,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:black_stained_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:blackstone_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:crimson_trapdoor[facing=south,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:blackstone_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:crimson_trapdoor[facing=east,half=top,open=false,powered=true,waterlogged=false]",
            "minecraft:blackstone_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:black_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=true]",
            "minecraft:nether_brick_slab[type=top,waterlogged=false]",
            "minecraft:black_stained_glass_pane[east=true,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:blackstone_wall[east=none,north=low,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:crimson_stairs[facing=south,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:crimson_trapdoor[facing=west,half=top,open=true,powered=false,waterlogged=false]",
            "minecraft:crimson_planks",
            "minecraft:crimson_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:black_stained_glass_pane[east=true,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:crimson_stairs[facing=north,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:blackstone_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:black_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=true]",
            "minecraft:crimson_fence_gate[facing=east,in_wall=false,open=true,powered=false]",
            "minecraft:wither_skeleton_wall_skull[facing=west,powered=false]",
            "minecraft:cherry_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:blackstone",
            "minecraft:blackstone_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:crimson_stairs[facing=south,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:blackstone_wall[east=low,north=low,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:crimson_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:crimson_trapdoor[facing=east,half=top,open=true,powered=false,waterlogged=false]",
            "minecraft:cherry_trapdoor[facing=north,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:crimson_stairs[facing=north,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:blackstone_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:crimson_wall_sign[facing=north,waterlogged=false]",
            "minecraft:crimson_fence_gate[facing=south,in_wall=false,open=false,powered=false]",
            "minecraft:crimson_stairs[facing=south,half=top,shape=straight,waterlogged=false]",
            "minecraft:crimson_stairs[facing=west,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:crimson_trapdoor[facing=west,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:hopper[enabled=true,facing=east]",
            "minecraft:hopper[enabled=true,facing=west]",
            "minecraft:crimson_wall_sign[facing=south,waterlogged=false]",
            "minecraft:crimson_fence_gate[facing=north,in_wall=false,open=false,powered=false]",
            "minecraft:crimson_stairs[facing=north,half=top,shape=straight,waterlogged=false]",
            "minecraft:crimson_stairs[facing=west,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:cherry_trapdoor[facing=west,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:crimson_trapdoor[facing=west,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:crimson_fence_gate[facing=south,in_wall=false,open=true,powered=false]",
            "minecraft:cherry_fence_gate[facing=east,in_wall=false,open=true,powered=false]",
            "minecraft:cherry_stairs[facing=north,half=top,shape=straight,waterlogged=false]",
            "minecraft:cherry_planks",
            "minecraft:crimson_fence[east=false,north=false,south=false,waterlogged=false,west=true]",
            "minecraft:nether_brick_slab[type=double,waterlogged=true]",
            "minecraft:cherry_fence[east=false,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:crimson_slab[type=top,waterlogged=false]",
            "minecraft:crimson_wall_sign[facing=east,waterlogged=false]",
            "minecraft:nether_brick_slab[type=double,waterlogged=false]",
            "minecraft:cherry_trapdoor[facing=east,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:hopper[enabled=true,facing=south]",
            "minecraft:crimson_fence_gate[facing=west,in_wall=false,open=true,powered=false]",
            "minecraft:cherry_wall_sign[facing=south,waterlogged=false]",
            "minecraft:blackstone_slab[type=double,waterlogged=false]",
            "minecraft:nether_bricks",
            "minecraft:hopper[enabled=true,facing=north]",
            "minecraft:crimson_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:nether_brick_slab[type=bottom,waterlogged=true]",
            "minecraft:crimson_fence_gate[facing=north,in_wall=false,open=true,powered=false]",
            "minecraft:crimson_stairs[facing=east,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:crimson_fence[east=true,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:bubble_column[drag=true]",
            "minecraft:crimson_wall_sign[facing=west,waterlogged=false]",
            "minecraft:crimson_fence[east=false,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:cherry_stairs[facing=east,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:cherry_fence_gate[facing=north,in_wall=false,open=false,powered=false]",
            "minecraft:stone",
            "minecraft:cherry_wall_sign[facing=north,waterlogged=false]",
            "minecraft:cherry_wall_sign[facing=west,waterlogged=false]",
            "minecraft:cherry_slab[type=top,waterlogged=false]",
            "minecraft:crimson_fence[east=false,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:cherry_fence[east=false,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:cherry_stairs[facing=south,half=top,shape=straight,waterlogged=false]",
            "minecraft:cherry_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:blackstone_wall[east=tall,north=tall,south=tall,up=false,waterlogged=false,west=tall]",
            "minecraft:crimson_slab[type=bottom,waterlogged=false]",
            "minecraft:cherry_stairs[facing=east,half=top,shape=straight,waterlogged=true]",
            "minecraft:crimson_fence_gate[facing=east,in_wall=false,open=false,powered=false]",
            "minecraft:crimson_fence_gate[facing=west,in_wall=false,open=false,powered=false]",
            "minecraft:crimson_trapdoor[facing=south,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:wither_skeleton_wall_skull[facing=north,powered=false]",
            "minecraft:crimson_trapdoor[facing=north,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:cherry_fence_gate[facing=east,in_wall=false,open=false,powered=false]",
            "minecraft:blackstone_wall[east=low,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:nether_brick_slab[type=bottom,waterlogged=false]",
            "minecraft:daylight_detector[inverted=false,power=5]",
            "minecraft:blackstone_wall[east=low,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:cherry_slab[type=bottom,waterlogged=false]",
            "minecraft:cherry_fence[east=true,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:cherry_fence_gate[facing=west,in_wall=false,open=true,powered=false]",
            "minecraft:diorite_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:diorite_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:diorite_slab[type=top,waterlogged=false]",
            "minecraft:crimson_trapdoor[facing=east,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:diorite_wall[east=tall,north=none,south=none,up=false,waterlogged=false,west=tall]",
            "minecraft:diorite_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:diorite_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:cherry_wall_sign[facing=east,waterlogged=false]",
            "minecraft:crimson_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:cherry_fence[east=false,north=false,south=false,waterlogged=false,west=true]",
            "minecraft:crimson_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:cherry_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:cherry_trapdoor[facing=east,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:mangrove_fence[east=true,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:red_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=true]",
            "minecraft:red_stained_glass_pane[east=true,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:mangrove_fence[east=false,north=false,south=true,waterlogged=false,west=true]",
            "minecraft:wither_skeleton_wall_skull[facing=east,powered=false]",
            "minecraft:blackstone_wall[east=tall,north=tall,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:blackstone_wall[east=none,north=tall,south=low,up=true,waterlogged=false,west=tall]",
            "minecraft:red_terracotta",
            "minecraft:blackstone_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=low]",
            "minecraft:red_stained_glass_pane[east=true,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:red_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=true]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=3]",
            "minecraft:blackstone_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=5]",
            "minecraft:black_stained_glass_pane[east=true,north=true,south=false,waterlogged=false,west=true]",
            "minecraft:lava[level=0]",
            "minecraft:diorite_wall[east=none,north=tall,south=tall,up=false,waterlogged=false,west=none]",
            "minecraft:diorite_stairs[facing=north,half=top,shape=straight,waterlogged=false]",
            "minecraft:diorite_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:diorite_stairs[facing=south,half=top,shape=straight,waterlogged=false]",
            "minecraft:diorite_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:crimson_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:mangrove_fence[east=true,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:mangrove_fence[east=false,north=true,south=false,waterlogged=false,west=true]",
            "minecraft:blackstone_wall[east=tall,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:blackstone_wall[east=none,north=low,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:blackstone_wall[east=tall,north=low,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:cherry_fence_gate[facing=west,in_wall=false,open=false,powered=false]",
            "minecraft:cherry_stairs[facing=east,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:cherry_fence_gate[facing=south,in_wall=false,open=false,powered=false]",
            "minecraft:diorite_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:diorite_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:crimson_stairs[facing=east,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:blackstone_wall[east=none,north=low,south=low,up=true,waterlogged=false,west=tall]",
            "minecraft:cherry_trapdoor[facing=south,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=9]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=7]",
            "minecraft:wither_skeleton_wall_skull[facing=south,powered=false]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=15]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=1]",
            "minecraft:cherry_trapdoor[facing=west,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:diorite_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:diorite_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:crimson_fence_gate[facing=south,in_wall=true,open=true,powered=false]",
            "minecraft:blackstone_wall[east=low,north=tall,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:diorite",
            "minecraft:diorite_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=13]",
            "minecraft:diorite_wall[east=tall,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:nether_brick_wall[east=none,north=tall,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:wither_skeleton_skull[powered=false,rotation=11]",
            "minecraft:crimson_stairs[facing=south,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:nether_brick_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:crimson_trapdoor[facing=east,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:red_stained_glass_pane[east=true,north=false,south=true,waterlogged=false,west=true]",
            "minecraft:nether_brick_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:cherry_stairs[facing=north,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:stripped_mangrove_log[axis=x]",
            "minecraft:black_stained_glass_pane[east=true,north=true,south=true,waterlogged=false,west=false]",
            "minecraft:red_stained_glass_pane[east=false,north=true,south=true,waterlogged=false,west=true]",
            "minecraft:nether_brick_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:nether_brick_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:obsidian",
            "minecraft:black_stained_glass_pane[east=false,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:cherry_trapdoor[facing=east,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:diorite_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:crimson_fence_gate[facing=east,in_wall=true,open=true,powered=false]",
            "minecraft:diorite_wall[east=low,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_wall[east=low,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=low]",
            "minecraft:crimson_fence_gate[facing=west,in_wall=true,open=true,powered=false]",
            "minecraft:diorite_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:nether_brick_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:nether_brick_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:nether_brick_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:cherry_trapdoor[facing=north,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:stripped_mangrove_log[axis=z]",
            "minecraft:stripped_mangrove_wood[axis=z]",
            "minecraft:nether_brick_wall[east=tall,north=tall,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:crimson_trapdoor[facing=south,half=top,open=true,powered=false,waterlogged=false]",
            "minecraft:crimson_fence_gate[facing=north,in_wall=true,open=true,powered=false]",
            "minecraft:blackstone_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:cherry_fence_gate[facing=south,in_wall=false,open=true,powered=false]",
            "minecraft:skeleton_wall_skull[facing=west,powered=false]",
            "minecraft:skeleton_wall_skull[facing=east,powered=false]",
            "minecraft:crimson_trapdoor[facing=south,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:blackstone_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:white_stained_glass_pane[east=true,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:white_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=true]",
            "minecraft:diorite_stairs[facing=north,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:white_stained_glass_pane[east=true,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:diorite_wall[east=low,north=tall,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:crimson_trapdoor[facing=west,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:blackstone_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:red_stained_glass_pane[east=true,north=true,south=true,waterlogged=false,west=true]",
            "minecraft:stripped_mangrove_wood[axis=x]",
            "minecraft:nether_brick_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:nether_brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:nether_portal[axis=x]",
            "minecraft:diorite_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:white_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=true]",
            "minecraft:nether_portal[axis=z]",
            "minecraft:diorite_stairs[facing=east,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:skeleton_wall_skull[facing=north,powered=false]",
            "minecraft:skeleton_wall_skull[facing=south,powered=false]",
            "minecraft:diorite_stairs[facing=west,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:diorite_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:red_stained_glass_pane[east=true,north=true,south=true,waterlogged=false,west=false]",
            "minecraft:nether_brick_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:mangrove_fence[east=false,north=true,south=true,waterlogged=false,west=true]",
            "minecraft:red_stained_glass_pane[east=true,north=true,south=false,waterlogged=false,west=true]",
            "minecraft:mangrove_planks",
            "minecraft:diorite_wall[east=none,north=low,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:diorite_stairs[facing=south,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:crimson_trapdoor[facing=north,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:red_stained_glass_pane[east=false,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:cherry_fence_gate[facing=north,in_wall=false,open=true,powered=false]",
            "minecraft:crimson_stairs[facing=north,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:cherry_stairs[facing=east,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:crimson_stairs[facing=west,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:crimson_stairs[facing=east,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:blackstone_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:diorite_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:diorite_stairs[facing=north,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:white_stained_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:crimson_stairs[facing=south,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:cherry_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:black_stained_glass_pane[east=false,north=true,south=true,waterlogged=false,west=true]",
            "minecraft:cherry_stairs[facing=north,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:blackstone_wall[east=tall,north=tall,south=low,up=true,waterlogged=false,west=tall]",
            "minecraft:diorite_wall[east=tall,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:white_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:diorite_stairs[facing=east,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:diorite_stairs[facing=west,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:white_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:diorite_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:white_stained_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true]",
            "minecraft:diorite_stairs[facing=south,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:diorite_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:cherry_stairs[facing=east,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:crimson_stairs[facing=west,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:blackstone_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:blackstone_wall[east=tall,north=low,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:blackstone_wall[east=low,north=tall,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:crimson_stairs[facing=north,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:crimson_stairs[facing=east,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:cherry_stairs[facing=west,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:blackstone_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:nether_brick_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:nether_brick_wall[east=tall,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:blackstone_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=tall]",
            "minecraft:blackstone_wall[east=none,north=tall,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:blackstone_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:nether_brick_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:nether_brick_stairs[facing=north,half=top,shape=straight,waterlogged=false]",
            "minecraft:nether_brick_stairs[facing=south,half=top,shape=straight,waterlogged=false]",
            "minecraft:red_stained_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false]",
            "minecraft:diorite_stairs[facing=north,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:diorite_stairs[facing=east,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:diorite_stairs[facing=west,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:red_nether_brick_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:diorite_stairs[facing=south,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:diorite_stairs[facing=north,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:nether_brick_wall[east=low,north=low,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:mangrove_fence[east=true,north=false,south=true,waterlogged=false,west=true]",
            "minecraft:black_stained_glass_pane[east=true,north=false,south=true,waterlogged=false,west=true]",
            "minecraft:nether_brick_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:diorite_stairs[facing=east,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:diorite_stairs[facing=west,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:nether_brick_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:red_stained_glass",
            "minecraft:nether_brick_wall[east=none,north=low,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:diorite_stairs[facing=south,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:diorite_slab[type=bottom,waterlogged=false]",
            "minecraft:diorite_wall[east=none,north=tall,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:mangrove_fence_gate[facing=south,in_wall=false,open=true,powered=false]",
            "minecraft:mangrove_fence_gate[facing=east,in_wall=false,open=true,powered=false]",
            "minecraft:mangrove_fence_gate[facing=west,in_wall=false,open=true,powered=false]",
            "minecraft:mangrove_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:mangrove_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:mangrove_stairs[facing=north,half=top,shape=straight,waterlogged=false]",
            "minecraft:diorite_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:diorite_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:mangrove_stairs[facing=south,half=top,shape=straight,waterlogged=false]",
            "minecraft:mangrove_fence_gate[facing=north,in_wall=false,open=true,powered=false]",
            "minecraft:cherry_trapdoor[facing=south,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:diorite_wall[east=tall,north=tall,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:blackstone_slab[type=bottom,waterlogged=false]",
            "minecraft:mangrove_fence[east=true,north=true,south=false,waterlogged=false,west=true]",
            "minecraft:black_wool",
            "minecraft:mangrove_trapdoor[facing=north,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:mangrove_slab[type=top,waterlogged=false]",
            "minecraft:mangrove_trapdoor[facing=west,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:mangrove_trapdoor[facing=east,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:mangrove_trapdoor[facing=south,half=top,open=false,powered=false,waterlogged=false]",
            "minecraft:mangrove_slab[type=double,waterlogged=false]",
            "minecraft:mangrove_wall_sign[facing=north,waterlogged=false]",
            "minecraft:mangrove_wall_sign[facing=west,waterlogged=false]",
            "minecraft:mangrove_wall_sign[facing=east,waterlogged=false]",
            "minecraft:mangrove_wall_sign[facing=south,waterlogged=false]",
            "minecraft:mangrove_trapdoor[facing=north,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:skeleton_skull[powered=false,rotation=0]",
            "minecraft:mangrove_trapdoor[facing=east,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:mangrove_slab[type=bottom,waterlogged=false]",
            "minecraft:skeleton_skull[powered=false,rotation=13]",
            "minecraft:skeleton_skull[powered=false,rotation=2]",
            "minecraft:skeleton_skull[powered=false,rotation=14]",
            "minecraft:skeleton_skull[powered=false,rotation=3]",
            "minecraft:stripped_mangrove_wood[axis=y]",
            "minecraft:mangrove_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:mangrove_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:skeleton_skull[powered=false,rotation=15]",
            "minecraft:mangrove_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:red_nether_brick_wall[east=none,north=tall,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:mangrove_fence[east=false,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:red_nether_brick_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=tall,north=tall,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:skeleton_skull[powered=false,rotation=1]",
            "minecraft:skeleton_skull[powered=false,rotation=12]",
            "minecraft:red_nether_brick_wall[east=tall,north=none,south=none,up=false,waterlogged=false,west=tall]",
            "minecraft:skeleton_skull[powered=false,rotation=4]",
            "minecraft:skeleton_skull[powered=false,rotation=10]",
            "minecraft:mangrove_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:skeleton_skull[powered=false,rotation=6]",
            "minecraft:red_nether_brick_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:red_nether_brick_wall[east=none,north=tall,south=tall,up=false,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=low,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:red_nether_brick_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:skeleton_skull[powered=false,rotation=9]",
            "minecraft:red_nether_brick_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:skeleton_skull[powered=false,rotation=7]",
            "minecraft:skeleton_skull[powered=false,rotation=11]",
            "minecraft:skeleton_skull[powered=false,rotation=5]",
            "minecraft:mangrove_trapdoor[facing=west,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:skeleton_skull[powered=false,rotation=8]",
            "minecraft:mangrove_trapdoor[facing=south,half=bottom,open=false,powered=false,waterlogged=false]",
            "minecraft:mangrove_stairs[facing=north,half=top,shape=inner_left,waterlogged=false]",
            "minecraft:mangrove_stairs[facing=east,half=top,shape=inner_left,waterlogged=false]",
            "minecraft:mangrove_stairs[facing=west,half=top,shape=inner_left,waterlogged=false]",
            "minecraft:mangrove_stairs[facing=south,half=top,shape=inner_left,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=south,half=top,shape=straight,waterlogged=false]",
            "minecraft:blackstone_slab[type=top,waterlogged=false]",
            "minecraft:crimson_hyphae[axis=z]",
            "minecraft:crimson_hyphae[axis=x]",
            "minecraft:deepslate_tile_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=north,half=top,shape=straight,waterlogged=false]",
            "minecraft:deepslate_tile_slab[type=top,waterlogged=false]",
            "minecraft:deepslate_tile_slab[type=bottom,waterlogged=false]",
            "minecraft:deepslate_tiles",
            "minecraft:deepslate_tile_slab[type=double,waterlogged=false]",
            "minecraft:red_nether_bricks",
            "minecraft:crimson_hyphae[axis=y]",
            "minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:red_nether_brick_slab[type=bottom,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=west,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:deepslate_tile_stairs[facing=east,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:red_nether_brick_stairs[facing=south,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:red_nether_brick_stairs[facing=south,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:red_nether_brick_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:red_nether_brick_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:chain[axis=y,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=south,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=south,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:blackstone_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:decorated_pot[cracked=false,facing=south,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:blackstone_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:red_nether_brick_wall[east=low,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:red_nether_brick_wall[east=low,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=low]",
            "minecraft:polished_diorite_stairs[facing=north,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=north,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:red_nether_brick_stairs[facing=north,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:red_nether_brick_stairs[facing=north,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:deepslate_tile_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:polished_diorite_slab[type=top,waterlogged=false]",
            "minecraft:mangrove_fence[east=false,north=true,south=true,waterlogged=false,west=false]",
            "minecraft:flower_pot",
            "minecraft:red_nether_brick_wall[east=tall,north=none,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=tall]",
            "minecraft:black_candle[candles=1,lit=false,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=east,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=west,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:red_nether_brick_wall[east=tall,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:polished_diorite_stairs[facing=east,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:polished_diorite_stairs[facing=west,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:red_nether_brick_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=tall]",
            "minecraft:red_nether_brick_wall[east=tall,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=low,north=tall,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=low]",
            "minecraft:red_nether_brick_wall[east=low,north=none,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:red_nether_brick_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=low]",
            "minecraft:red_nether_brick_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=tall]",
            "minecraft:red_nether_brick_wall[east=tall,north=low,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:red_stained_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true]",
            "minecraft:red_stained_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:mangrove_fence_gate[facing=south,in_wall=false,open=false,powered=false]",
            "minecraft:mangrove_fence_gate[facing=north,in_wall=false,open=false,powered=false]",
            "minecraft:red_stained_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false]",
            "minecraft:crimson_slab[type=double,waterlogged=false]",
            "minecraft:red_nether_brick_wall[east=tall,north=none,south=none,up=true,waterlogged=false,west=none]",
            "minecraft:mangrove_trapdoor[facing=west,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:chiseled_polished_blackstone",
            "minecraft:mangrove_trapdoor[facing=east,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:mangrove_trapdoor[facing=south,half=bottom,open=true,powered=false,waterlogged=false]",
            "minecraft:blackstone_wall[east=low,north=low,south=low,up=false,waterlogged=false,west=low]",
            "minecraft:blackstone_wall[east=low,north=tall,south=low,up=true,waterlogged=false,west=tall]",
            "minecraft:blackstone_wall[east=low,north=low,south=tall,up=true,waterlogged=false,west=none]",
            "minecraft:blackstone_wall[east=none,north=low,south=tall,up=true,waterlogged=false,west=low]",
            "minecraft:blackstone_wall[east=low,north=tall,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:blackstone_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=none]",
            "minecraft:nether_brick_fence[east=false,north=false,south=false,waterlogged=false,west=false]",
            "minecraft:red_nether_brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:red_nether_brick_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]"
        };
        for (int i = 0; i < paletteStrs.length; i++) {
            PALETTE[i] = Bukkit.createBlockData(paletteStrs[i]);
        }

        byte[] compressed = Base64.getDecoder().decode("eJztXQmcFcWZr69aYAzqOu+5eUwyLG1ko2QWJWxEsol5AadQ1jV7BIOwiUt8yooXcd2FScxkFA131GgCarx1vCJCuDzQEYZTMEajRCWKMTGXhDFq0Cgg+/uq+qjqrupjDoaB+vc8eK/7q6Orvu//fVXdXU2IhYWFhYWFhYWFhcVeA3R3BSwsLCwsLLofcICXb2FhYWFhsQ8ADvDyLSwsLCwsuhtAALrZc1p3bGFhYWFxoCO/O4ae4Y6tk7ewsLCw6Epk8DPQk9xxnvLzZNsluVpYWFhYdBVg/6pvTo9p3bGFhYWFxT4B6BGj2FAYUr1lRgfHpdEdZxKHnO4467mJ4mkWUZovzjjAccA3gIWFRU/jjE6uQuCxMrnj3P4FkjxX4I65i0tzs3jcd8dJ7lDkw4fRGX09CuZwxynlK+4481gasjlv6HH6uh9W1cLComuQb8jX/aThu7lUKe6+UnPzXGImZyD8W65RZKKfU9xxyqgXZHcMqe6YC/JEqV3GM+T1SMzVrwTPkaa3AgpJ7tiYgBcKABQw0wz9GsQOnXYZQJJKTtB12p8r0rOwsNgLcHqQO+6Gugp3mIVns84B+64ogzv2nVa2FgtGvNncsfByibI0oyigW0X35jnjDO7YA6ZLrGtYegZ37NUg0TE6fozjBw7p/YrzDd7AP8N5ZR5ye3IJ4k4WofbCumMLi30NB/XKLNo7R7Z9Eo6pNFCVnJFMwwdH6/oRg2AqAnrP4hI9P5cm6DuOZHCP4Q/6smTpDTtTKilGexlcrMgxkztWkeDovcOKdEKusmiiOxYnpOScubaGjPseEo64/RaAJH0PTj6ptQ4N60DTmpXrO59+9+f4Teh7mDffEszWZwlJsrrZfLfodQb69OkjG6yFxYGCv8kqeHi14tSiKBTC78Uj/jZRUpL9aKmfWRIU0ZojPpaQKwCEoh+vVQ/2/7sBimRGHgoGRukERz0Xp+Uuj4RFNqE7DCU/0qdPn6ik52My+O6o10g+Jdkdm6QLhYLis0QCN4OkD1kdZFHlpMSJFbSy6ul7CXWihLhRF2uUjHtjY9PWHIkj3SyinziqNtJZxkwHlv4+Wgm94CfJ0UdVK5KqXslB7CdJ8RjvckGQJ6SGu3xeP9uV9gIA0fW9TlRpd5UvBn2q7h9Moopk/8HHHkcUWjB1JiFkyKeH/iPpIsjWaGxPXvXPSN/VI0YoR3NEHzZQ6XgnanYfH5OI75EP1A3LIov7B+pc3Gdiuo0VOmH4Z//JLFv4nGJdnz/xC6YalhGB7BdHjDzJJFko19fX15c90Y98tOQGlT300EMVXSswxpjrixIyamQkr0FBmxSY67qSaBQnHxe2CRLWKZKo3JTD6gg5afhoT853W9ohtdTKWir+57pPDRLfTi0NDWrOBf4lwsUDybHHDUaR0078UpB/hOC9vf86/N+GiG9DfE6L+UNtCxQK2EWSaxNwNX6rUK533VPifouxcjmWaT1zAYJgJMiWBV0cZMpFg1NXRGOyPFd1wEu9XCPVLZcZI3hxF+DfQ+FTXDdaAdFaIlsZiubKiLtj3toxuf4jRG9JjaCPcv5joMvdsamzPHUhhHx5zOn9R0WuFsh5fkWyxFNLY0f6N9OFsp7wCWND+z6ekDN8nS2UT8FaupI7llnjeEJGDw06A02LFeRaDh0tidbwuMETRZP1RU+P8sXAcbVaGuhfV1JYaPD4kluKaO7nxA/vDI7341eeazW3WyFbCLvds2MZxVryn5gDJ46gLz9Rpx0+nPrZ4SOjZDpQjRMw0u+H/fV5/DpUOY2vjviaLho6Sez8Utg4h5LTRpmYlROiZ/GCss/M7qdHZxftYRiWbTf+/i9lT2Bj6m5CJqDChKqMXHy69823BA9fHoGdddQR0q5TS3UjFQP28PVRXyM1Z7nD5X1coU4b8xXvZ+Xssyv4/xmkHymeM2CiLCps8L8/O/ZcbjGTzpt0PhLw0UM/xsu6IN4AZ5QGICVeyC6azOo9sj79xG9cPCgeFI8ezj1suVKplBk3mv51pf85uXRsP21QXGAM61mpsLJ3EqMvGRIJijkTCr9d4dlyA5PIggMb+X/d0v9NgamEMM4YnDQa4Jt4Bt+SvPyl38aKjCLQiHzGgjGB+C0xDyFD3e/wX01R6oXL+J7iuH6XB4fGD5wGkRG7ipJbGi+aV5hbQesi0BvUjBtwBUQdEuMFB/9g3Rlj5SsjhZbrWaUsZIGi+xCi2CQR51U5HzsKRQHgu3zDPzzkMlYpTwfVM589A2ZChfAUxE9BvRSE4ZFZUFFSzIbzggShfJhgDlx0tlKlGcDzkQrg1fLOt0Iqc2EWKEkI1rPCsB+B0liKSpmdr9SJFLAtXSam9IMGIqxcCbQ7zBubmH/zIwev3aNBCyGDom6ci8quw8fA40rfyzo1PGHIJaPJlJj6TQ2O+1+GETL+jO9Ue0qMwFP0lZqcNWB8mCchde40qL0KUI15QOy1yFUAV3P5489xPedHyGkjvkGuge97+Ra4cVckj0wIuTY4TMhXR10HwbWsMqtwAw+kVXoZSAYM9r8Xyh5toGiNqO8PYOwPwaeZo4cOHh+YZ7mezYPZwC7kHVE8xx3rhbwXBJY+uIpc+u0+PEX5/PkwB+YD74uaar++18PQTw9RrgcMR4O/9AYIKZQUx5WKtboxwkS097NciciHjR2KP7Eq6iDhRsBw4Jx+YR+QM0o/gtJNQMjNaucO4cw2kAyQGwuD/fEG38sjggA82Dd580hEIJ16HMaIgGSPCHoKLs62e0KsBX3ljYVa46Ww2N81kPuS6Dj6FijdCqR/OJjj4PZJyG3gH5gN582F27mqjHXrYlPDgQFOPANLOZ9MvgPmwp1wHiF9x5XGSS5NoFhbjfH4WPcuqCXlZribp25G9u6N8axqpvcABtnH+8UE3HcvsPuA1JzF9fpk38d6gfbxNUei3XAHz8HuBzTUgFcEfgwYaj8AOP1IFiD7C1RQHEscVqdEQIdXF2vJyaUHYQoshEUg+IUzDfr64sDSsQq3ctP9CRxVvZgzoYghKtxZNC4GMnr4ScoF+jORXpbAMZ7D58TIv8FSvqe30jDFY8gyWA7LNWS+AB7iez2HH8DL8GHQbZ5rIY/Ao5EsKyuAVMouJnR9oDyeThkTKNKzoVn4KY087+bzFfHH4HGRvsIi8qI3WiKVmTw5SZrMRa2TKyPU1ij/BFwky8+Bmcny82BepEIrIUl+Fdyhyp/PW6eiaR082qxWhwdfqDIxabdcIa1qvCPE07tY6FSI/n+HSrsIVms0aQ2sgbX6cGFKTEsx2NWg5kih/q6n/sxTf4TMDRhNrINi7VWwHkMDHpWL+PwhuAo2iOBg4LdqJyhM57nkJwPj3QgVJp9KtUp2jiCvJyFoBhEh8ppK1anjTp1jE7Cn/AyRfg7nYsVxA4Lwu0bQ3OHVnF8qwgDuhWYewxZrhUGFEXix9qeA3FCsRf9bhWr3NMyEx1C30DoO6kVqqvvXjfwZ9FMjcUeQRLEXKu5MmCO0pab3jTCxeEyU83HsUlNdrKmWWeDSb6NzFQO+ACe7pQcBY41wNgPB4xFCLlFyxcELjk2UEWDi8MMLNTJ6dylKSUOOKOFAQsaAghDyDLjR+YWaQzCUjO0m5NjSceqOwdy7+bufhZ8DfviPCYQc/FyENdC2MNfnoOZ58Hl6M/cVj8A6GD8hdqvYwbWHcE64DXqTzfALeAGQ+l+EmTAbfgHodvoeFqvm4N6njfgCL+wlzw/xNOLiu5CQhMeTr47qe8jHa8kWebS5BUixNj4VMbhqIOmHQwuJQDl31IxQ46eDevU97OihZ5Ip62FhGFMgNy+ExTD1l1By1SGYN16pWgyNG8CVohB3A2fKUedGb1avIqTvy/AKbOW8ukXktgUwtNjqRQsqsKleBT5QFZTt0bbL2K804ptxEFJmLnkYXottDwNyOSn/GrshgjnwG+Hf2OvhsddBTLU0i4Mymn1/+ipEUnjV+m3U4f4OXgyyiSQRX+ZGfOjvAxmtOOao5p8iHubXjtzJbD/C0MujoqsFkMl/SG6hyYGe+xBmZeiEzWqEhHgR/ghlVDdzd5crhMQ674JcOoV4w9PYbeL4Nk9j/2QQ73uI1iS2AhlWN0hzc2tvjB22gx868ATboQ3DiWhsjvAoRzJRYdujh+LoVCGkg3uR/nUjiVdvjnLw46BeJGQiEZ4MxGlLEthHM7wJ/u24vaX4umrC+HVQhUdGfAP74aK5wqbmwZ89Nefc8BZIsfzBvbg190bH/AiQt8EzKy92RaaoOrZ0nEpgNUd6J4zRukzWSIt9D3sHXHUgzcdEB/Xqi7dUhvDmIiIRAQ6ISO8zx98I6k3EfDwTxV+A35UR893FY+Ky+p0W+wR2wMXvxswWle893YGav0Lpr6DRB/2Bj9c+B7rOx/2qSurgEMczw97vB3RL5kIrOKbnvsYLe/8AdvriuwCDfv0d9Hwo4eAd6/PDM52ENulHGTLqxLQDk2SbOd8Xj9gdbygcSkxpw8hB2ssWwnoeOXwYS1CsJcU90IY8eb80IHwVxm2AxjaoOeIy7Q1KR/HgQbiEIHjYCq/A5VQfyDM2zuVzGMKzEMLWQGwsiXgfWmEGeqBtwEwOhVXIDJgB02hr7HwmX0G13o5X9Eoqhv+a6um9rx4VRTg+ilahCJPuEs5V52ytMQ++y9u6og0sptPoVAchK2AGnQWzgFQYmLp2C5BmmAUruP3Ea8aWY30kPXLHadUoCBeCaEHIt2njWwFuBeOk4KPyJHArIJEQ3UdTG4YLcvVEuBCP0X28hVM1UsQ1iWlv5OHggyOVIQQ0FDQaHfD7MNM31ll0duKNheiDV8jk5rX24dVvgXD2QUnGB12LL0Pp5ci4XceuggTn0EvmRqvUO15A71yD9arMOzWDPcNOix6GKjJY1+e63V7wS7Lt3suQ+FJ81UYP3vylxCHNcB/oLadqwvgJVbpooA2mknWgbwfOgoo858CqZJINpTEOWArfo/qHB5fxEV8gz78b+HsuH4cyV+8pMIvmkME66NL3ES/dE4WztnNHulOjM4brClqFbINX4Cqqia0RW7m+i5tiZIXXhdccTZhdxOs3cqev9fncpV5NN4UTir711hxxDU3wq2Gsyr9Fr5t6+D695NpMq/UZcVAvrdvWoTe5IMoz3bEORnvRk+pq0XEYwtfEqLa70AkVmrIBFnrX7lVXry/NEcwni4vZ0SRixbsmfCwDxn39dSb+wQld9gP/6A8pI0y5uBrFJmB672Bme4F5VHFC82iP8Jw9UXi+2tLzk1t6mbFDJTWKYQFo9IYlq6WkIJuAkcalcL0hAiWNOn/faFrBomlDZIy/CLi7D29fjPrSG2JtUpXVmWrWsegc7JOUZ2FhkQ8NMR+/ABbCBq2T52iXk5fFDbcECCyCnC6emBxCQhLr4PdZB9+e7tS6d0WlNRop+esm7t6NQSd37yTi3UmSd1f01XfvWqALvbEjo23rgy0sLExoaFTn6tG5Nxp9ey6qa5dnD+ZcE4dg7Xbrdo5+7wjnaud2dCWL6UoGf/42KA49WckD4TSH3hjx52JyPqHuFhYWFjmQNigyunOWOFRvhzuXaHaBNxufzNE/ElW/iQqPHozC4lhknLtNHN/ndDY3q8PNmw/0gf0tanvckjb8ztHWC4wdanbWODrX6U2yVkoKsgiS77nL793jV95JNqROGllYWOynmAW6r3rId+g2J3NwOzx8IY+Hl0bszPR0XsjM3MsXCrguiufxdZjEb8Qy3lxfIM0g3XbcsbFklwkXFOFCdwl3f2tgbxbMvUnMvck0GuP5ebM23uoJNDGSwbFvDI4X8jp2/tydGTdTxUjT5o5mgO6rhYXFXsX7IRtNij++FUHhA7iNKk/UJYJJ9w/PTeXXmVn5o2Er3kEfShSMt9VxbIBGkJYYYwyvwJuE3+DLsnnSBb7smYlT/aVSwkel+deC9hG6yc2AuRm8AmFs8mTd43MzQDw/xyKDVl7K7dREnYWIsyrs4z6za4UztsYsuAPbuhBra/x/Op2lfXwOVxBiSR1bwDURtE/P8dXyNAqUrJhN22G7WGsvSTd9rb/Tt9YCqn2bUbppK95V5zfMRnyUNNXjy1F5LutOFZafnLuLzqYpMR9ZIXFYKilZWPQ49B/ZX//IaxST+AJm3pIhKcDVSZqFD3kR5ot1eJKxDEKjfxGY4QkeH3dTabC8JyXvu8V4OYMwv+WOrzHKUWDsHprg/ts4EXqZI+cm8aBgWZmRTRRbcy+9V6qyX3N2H72Pam6m3szrwMxrufFVdU0r8IjQIdgpIgamX4FH+Ck+ApUTiKreH3Vjw4Lld2IJ+JdJYjnHAP66InrpyArXw1KER7c7Z3KvT/l6cVRtdQmUGfBjEUnFEnDvwpc4UMGNyOszOQFPoV13x1v61tjFiFiP4Q3yD9AHdLp0JURXZM6vp4QQXLDPD0wX4PUDlnTHqbfojhcMLKComdv9BftMWBK6dMYeTJnYl4RJqnAxNIrm1OdO+KI7k3iCWbCQhktLJcGzopakSbZ2cbGFRZfhfVgJk7zlUNOwiE6nM+ADmMRX8U2FtIhvWuTNV3YJamRaJ0wn7eYQLhhXIBOYsh6mIk1hbQtIwQ3rTcuXingAF7PxsQ3CBUw1MK3X3xFsAdziJ/UqMHEolqKwAtww5PEhVuKP7BQr9hY07oT36CKqXbC3EBPHxmwJx2ECuMyPOBwV180g3QszaIL0NKoGF8EwTi/OV6qRsQt4sKuvenyt3kVihlrTMAXtUr2eN1dlXea2aqxiG+Cm7VFxiHQQDTE1NAa8fH3eLaGCb0lWcH+BXpcVFlCygHIDalqf7O/xxFCcLKC4pdinSOCivIgosog/BZgzT5CpAFJQF+pNA67SOx9m01lwBY0YhQlPwHxoSZ/2tLDoYsyi0+msrPfPFObCT+jcKPObwC5kT8EM4GuEpqHiudw06/ykT7OeX8LfeiymuHHpAsHLoOEuLZbQBmRCfIkIooJM+c2leunPLKHQCMvkg8txz1L6RUPeOudvyJwQ8hBN25EbFeTxeEdUdDvDF8zICFd0D7GI8kvMcdlCoTA94t2upJPRK2ulCWH+onM+dsHD4jKGRp67+EeoGlJcSSczY/aTotkTrJ+p6iym4bqT9951lK1NKxgfZjCEZDxK03Yo+hzZBVM7TZ/Fa3pka2mCq80avYLiphijv8uAx/AQw9AAN2HsfF9qKCHks3BOmc2C94FdmHYRQWARnQmP05kZRjICO+EKGqwaamGx7wPfw5FRslxOd+uDfMlyuYWbbuy1gQH6T8SZMHzRFmNcVuzQ4oSJ53ovACGkEv6OY9gz8ARdSaeuoqatYSV9gj4DupcsnjZx4kraCG3QBq00uuFeaFxJJ07Uvc5y9Dug8/fvRCaSA6ymsesIbbDGSHa5xVujx1qpQbyFttCKKUFcN/DNaKb8K3EFqZQTxFlMHsWZQZzpxY11j4ujfIK47mSNdcdmIx1t+y5WhGHPgCYg6Ardv4eupJfBWmramlbSe6jRGIQ1V/hrpMLfWgiOaOEXInj3JpCGeLFcC+VsVEl901xmjstLnBYW+xXW0fUmglpP18UObaCt9EkaDwUGhYci2Igc2n+Matn4u5Vu1Ja8lp4w5joQg33d9vUx566mRo5cSaeup6YNjxooc8wYpMxHqWlDyhwzphPChSV0A10erf8y+iQ1jb5sApugkxLkCiKERTxETVuyRWAMsZGaNn7YZCFrOAGICQbd9vUx567Snt96M9VoSM7nq2ggMcREZesMhMVJLk6VFhYWebAJbeipqCHxHT/VmdfTlPyMwjPqoWcp/JziIR2eo8/TR+lmKl8zbRC7ntOn+AV9gTY2LoQX6Ut0i+bzS7oQGhtfoC/rkr9CYTltxJHYVqr/QGPjMgqv6hL/ir5Gvdu7JMBSeI3+Wl/Xpt/oRpS/ocYbFV6ir0dzep2+ZGSy3+qy/51R3ObeE3Jv+L0u998rJhLiWfqCXilfoBE77AQL+AN9jTY2bue290fN55d0OzQ2vkbfMBv7Q3Szqv5NYp/B2p+mZBuFiHlto/AnA6Nsx51t0SN8x5s2ILCwiGGdgVkQDdEouklIr6fGP54o5uBEulW0lSZ/9Km99BmS61Pz9Mvoa3S5aTKiQRw1pMYbBnCa9jWKH90mjrWB9saCDXQ1XU03c4H07Xm6hq7RTdzgZDEGRm18LriVz/220tV0LV0T/FpLcRIbAyiUNtSkCYtZY8wDRVDiMkioyAZeEfz2Z81Q9C1vZvt5+mRSRUQmWMqyoP7heSz3aoKZpNZEZBKelH8iciapNUGBZVQ+KXEiy6XTSa0JXgfDmvgn5ddhOb9ClqtN/H/DE8nVJlh6mAmW7meCR3K3ydvezNs7+dskPB20Utzw/5y9E56InIl/UhlrIp+IvImTSq1JgzAd/zxQx1ZJv/CcUGJqQj0w2sE8VhnzEFryUFI9OkwmeKsLCrxA8aPbxLE2MNwS04CM+gJdbpxWahKH9e5F8LQw1qSP73B0qbMk16X3fcRGavzTpTP6BkSTnW6y6Ol4mqb8dXeqVroewg+SedJvTZm4LQZZKOmzGBaDSKOpibhwn75pSdyvyWLQPPHaBqkFa9LsA+W0mctp64nns7+VY/unEw03G4WsT6pJh8isRxC2hUU78BfaQsNPqvgOatrMad6lKX8aPJ2W5l29IbQvHZIGkHfpesj2IZxoYoVnTI2fGJW+R8MtayZhikhmSJrI11k2IZtQGy3tv5deuCaVrqwdNFdhsqLx71mKUxO1t7y/0hwFvh+ka6G5iwxvybVlJpbZg7SnPbbRKXbYCSSQldcSatMhcuwkgt67TqW9rq/9jtbDB7SFhp9UcYv9EDvoTtpCd1Gi+2uhOw169C71Uu5O+fAM4vorLIUQNwqRd8xIIEE6wgKCVfjOyC3Q4rERj3w0NdIhtjvVslQBPH/xOxvB+jnslPLAR29aqIvZaLkdU7hCKNy9i35I691V5jSrqFv/Ifa8WlCGYqS9O3kpxJiCYBnyudgybBkZyhDau9acZG1Me9tlJZ1hnjkZIRfbtI/NcrBlbibuMPV3wOtYWOxQXVaIXRqleZcS1yjuRpUT7czdZVZMXz0xKcRszkWV/tD77Ja+6/btpK5qiDuo67q7PbuK2aIwJ35APsldFLed4pDGgnmGO7mQ2goeV6KNR+HGONIr6EP6oSkFHooWIYpRqhuequZRYlEEnoemhN2GAnKXUG84g/pOyT2hgTop/92mFJ3WQnunjK5tp67u5S7U0vZYWk5rbidrtIuhOk6MHWLlfPyf17tYWBgVRqs079H6RPF6RX930PrdydnvpvXxeCAxhVHAZFrGnLjRpZm0OY8WWs/Mc5e4sXrDiiN8cFhfH1+2w9/q66MzG2rJKlO69UnN9WFU2sDxhDQwNjWeeQsVByJ4A/bQ0h7BpWoCbDp+LL5GeRMrlZimBNytuxESF+7V1J8v46uHrvqd0jhe7hF7kK/sdEr+WWu/xdQymuWESUNCs3dWx2L/6aovjnRN65j0vkP2Jeza3UHdVv6v9Jdg0B0kk1z81Q6WzM3E5DInhekjsUc+P2JxwKPmcifx+DRHeuHMFc6VydLfda5IFugOGNY51YGVkLnj1r8FWMm09CVj7ibqb+Ipj/C3a35NOKmU3ef5/YNP03V8E983UzdxLa1pThuspLqtDQyd2cDYdH5EZm7+fboTCyqauHNhFTLNUcQvd0iF8WMxT7LJWzA3mn2FGV8eEs88CbF6G7Gf5rvM3MKxFx81pHZgtMcT1cPwaEw71LADas+Y+yb1N/EQYPjbbGSshDFq3J63me05B1t0I2Y4M5M1cJYzQxIoprK8/pVHFgcodtOOCux1zHa0L6m/hc7R6v5cR8MArPQ9vaEEDHOVg1t0bwyVyjQU2kCvdq5xvu/wpzQvd1JWvrzWWUrJBnqd8wPnh5hkCZ1nMNuGhf6rSPQ0HFJwKCnQtIfuoYLtZb73vk138HCE8ec7YRrZpXjOSqS5PlbTiqEMYxto8k5ALF9ygOWbuX1vyNJ/N6rlNGRQE1Wv+AtyM6mkJNp+C4ja2Y+cm5yb0+0slx3noohbnJt19HMzvXWfGxH1QHK36E7c5nRUoFPQoF8pS78bJ1B1Zs10E6eeX4yQYEieer6a7+iWs4l7QgnIVv1vd/rc7oxEoiJpQEK8wyF3OuQOJ4EMsY5hEVH6lQdksmTst0/0IeFHxZH7g3IC8SD74GAc8bxN0GVshs03a765ei6nXrRfAfMre8yaDk23phsczVIjGnP3Qx+NEYswuBOYxrBIpGn//srmFhY5cJejNT4012aNvvJ5TpJ5P3f/WnGT8w9wt3OVc3c2i0G+use5xrnXMdNVw9QII7bBRtoGET6Upe5zlMhFpV9lMhaDmTupMYJxow7EHMv4LiSLZ9JkbITNt7vzVTxlLGPVZ6JNXp9J89B5ymbapBiVUHMS03JVSjkNQu53bnJ+nGBI+c2Ue37NfoPfz0kxaKZ6xx8xSgsLC4litAdMbn8PfUBn5Qt49K458KBuEE9I08LOCoL5BGUCTUVPBMlwE42Of9R2QC5RivCJN3LtNYlZ3Iwuw3ca2VxRj8t3ntNFGZP9Kt+7MmucrM1R/UPdfjOm2xFtVs+A/5fxDNKxSDMPQEjDT3T5I2Es1h1YYuAS43lYB29hoYdhFk47Y8eHEUt18svUkUiIW/WGZ9jdDnCGMvNTdORwrbPcicxsNsisERnyCJ6N3lFlHBdxBs/mG4R3yOob9qF84/fKa8DwATTjvWsKljmsh7ZEJ+SrzDYZtE2WiQ1hr3Ueiupzk9GbpxmLh7czT4M/7GTffUMSd+hIyDT7pb3sZ2FhkQv6EbxxxH+fYaDeiaH1NCeJVWPVitKqmfdSco4iqx/oofnuoQlPRQRoYBXi4qMFqzOw7RvAWPY68yy7vzGWUndJduV1e5wap+Eu/WBcywqmMXTC3IGFhUUXQDs0Nw3k9aOB1KvqhOhelG3AePOhjZFiTrv4C8kCEp6FR5yfZw/1h2aWJObH1feyrJ6C9cI4gMo48kHx+Y7p2b/Y5EfGaj/qTfJ0f+utcB5zWuhjzuNZnWGLU9eS2XGm6F1MpS/JrtJJphIbfetfGW+YuAqgv03HNGpOvl3WwsKiG6EzZr3ZG6alDaN2BRPMh2Kv0o7yl/lN3uRxGLoqq/euecI58Ql5qYMkFGvxr9th7AcNMnvuTodh0nUvo6Ya/zKhuNI58WXI2r+PQ12CknVEfcmZaWXrRsrGgE6rAU2aJY4tLCx6HNQreaZdxiF5FzuI7Jf0ElBFJpCqbKKrnF6kb2tGx9Pb+3S3k+7MSxnm3t+79ydhf2Xss9VONel7Q8aKFGvP7LI+68q+N4yO9cFz0n0eFhYW+yW0tEH2H+TwCTdS/5+uQA4XmWUeI0/Je+jSzGfVdW5gjeP/081hUndgfzczCwuLTobm2lrS5bb9GWsd/59uxrpOrsP67j+nfaZtuwPWxiwsLHJBcyUt6eLa/gy+zEXGJWks8uCAbllrYRYWFnv/wq+FhUUm47L2ZmFhYWFhYWFhYWFhYWFhYUHai/8H6FWbnA==");
        try {
            Inflater inf = new Inflater();
            inf.setInput(compressed);
            java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream(109581);
            byte[] buf = new byte[4096];
            while (!inf.finished()) {
                int count = inf.inflate(buf);
                bos.write(buf, 0, count);
            }
            inf.end();
            DATA = bos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to decompress schematic data", e);
        }
    }

    private static int decodeVarInt(byte[] data, int[] idxRef) {
        int value = 0;
        int shift = 0;
        int i = idxRef[0];
        while (true) {
            byte b = data[i++];
            value |= (b & 0x7F) << shift;
            if ((b & 0x80) == 0) break;
            shift += 7;
        }
        idxRef[0] = i;
        return value;
    }

    public static Set<BlockPos> capture(World world, int ox, int oy, int oz) {
        Set<BlockPos> result = new HashSet<>();
        for (int y = 0; y < H; y++) {
            for (int z = 0; z < L; z++) {
                for (int x = 0; x < W; x++) {
                    int wx = ox + x;
                    int wy = oy + y;
                    int wz = oz + z;
                    result.add(new BlockPos(wx, wy, wz,
                            world.getBlockAt(wx, wy, wz).getBlockData().clone()));
                }
            }
        }
        return result;
    }

    public static void paste(World world, int ox, int oy, int oz) {
        int[] idxRef = new int[1];
        for (int y = 0; y < H; y++) {
            for (int z = 0; z < L; z++) {
                for (int x = 0; x < W; x++) {
                    int wx = ox + x;
                    int wy = oy + y;
                    int wz = oz + z;
                    int pal = decodeVarInt(DATA, idxRef);
                    if (pal != 0) {
                        world.getBlockAt(wx, wy, wz).setBlockData(PALETTE[pal], false);
                    }
                }
            }
        }
    }
}